#!/bin/bash

#*************************** Arguments ***************************
# $1: Id
# $2: Binaries absolute path
# $3: Repetitions
# $4: Results absolute path
# $5: Output file name

if [ $# -lt 4 ]; then
    echo "Missing args"
    echo "Usage: $0 <id> <binaries path> \
<repetitions> <path to results folder> <output file>"
    exit 0
fi

#************************** Definitions **************************
# Scratch directory
SCRATCH_DIR="/home/christian.ponte/scratch"
# Thread number
THREAD_NUMBER="180"

# Auxiliary function
# Arguments: $1-repetitions $2-executable
function repeat_execution {
    local _return=""
    for i in $(seq 1 $1); do
        # Need to echo inside of $() to read all the output as a single line
        _output=$($2)
        _itime=$(echo $_output | sed -e "s/^.*Elapsed seconds = \
\([0-9]*\)\([.]\{0,1\}[0-9]*\).*/\1\2/" | \
            grep "^[0-9]*[.]\{0,1\}[0-9]*$")
        if [ "x$_itime" != "x" ]; then
            _return="$_return $_itime"
        else
            >&2 echo "Error on $2 iteration number $i"
            >&2 echo "$_output"
        fi
    done
    echo $_return
}

{
# Store files generated by execution on scratch dir
mkdir -p $SCRATCH_DIR/$1
cd $SCRATCH_DIR/$1

# Set unlimited stack size
ulimit -s unlimited

# Set thread number
export OMP_NUM_THREADS=$THREAD_NUMBER
# Disable thread migration
export OMP_PLACES="cores"
export OMP_PROC_BIND="true"

# For each executable
filecount=$(find $2 | wc -l)
for exec in $(find $2 | tail -n $((filecount-1)) | grep -v "$0$"); do
    echo "$exec $THREAD_NUMBER $(repeat_execution $3 $exec)"
done

} 1>$4/$5 2>"$4/error.log"
